# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.
# Docs: https://gohugo.io/content-management/menus/#define-in-site-configuration

main:
  - name: Home
    url: /#top
    weight: 10
  - name: About
    url: /#about
    weight: 20
  - name: Speakers
    url: /#speakers
    weight: 30
  - name: Agenda
    url: /#agenda
    weight: 40
  - name: Register
    url: /#register
    weight: 50
  - name: Travel
    url: /travel/
    weight: 60

footer:
  - identifier: home
    name: Home
    weight: 1
  - parent: home
    name: Home
    url: /
    weight: 1
  - identifier: registration
    name: Registration
    weight: 2
  - parent: registration
    name: Registration
    url: https://go.iastate.edu/EX30VZ
    weight: 3
  - parent: registration
    name: Abstract Submission
    url: https://iastate.qualtrics.com/jfe/form/SV_9yss741KCFfKidE
    weight: 4
  - identifier: legal
    name: Legal
    weight: 3
  - parent: legal
    name: Privacy
    url: /privacy
    weight: 1
  - parent: legal
    name: Terms
    url: /terms
    weight: 2
