# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: red

# SEO
marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo conference theme powered by Hugo Blox website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: false
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "logo.png"
    button:
      enable: true
      text: "Abstract Submission"
      url: "https://iastate.qualtrics.com/jfe/form/SV_9yss741KCFfKidE"
    button:
      enable: true
      text: "Register (coming soon)"
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  blox: "sitemap"
  content:
    logo:
      text: "PI in Sports"
    tagline: "Beyond the Stats: Unleashing Predictive Power in Sports"
  design:
    columns: 4
  copyright:
    notice: '© 2025 Conference on Predictive Inference in Sports'

# Localization
locale:
  date_format: '2006-01-02'
  time_format: '13:04'

# Extensions
extensions:
  convertkit:
    # To use the ConvertKit Newsletter blox, provide your public API Key from your ConvertKit account settings page
    api_key: ""
